# Additional languages for multilingual support

additional_languages = {
    'fr': {  # French
        'main_title': "🎓 Prédicteur d'Admission Universitaire",
        'subtitle': "**Système de prédiction basé sur l'apprentissage automatique**",
        'student_info': "📋 Informations Étudiant",
        'predict_button': "🔮 Prédire l'Admission",
        'pdf_button': "📄 Générer PDF",
        'error_found': "❌ Les erreurs suivantes ont été trouvées :",
        'complete_fields': "❌ Veuillez remplir tous les champs obligatoires",
        'success_data': "✅ Données traitées avec succès !",
        'prediction_result': "🔮 Résultat de la Prédiction",
        'likely_admission': "🎉 **ADMISSION PROBABLE**",
        'unlikely_admission': "❌ **ADMISSION IMPROBABLE**",
        'admission_probability': "Probabilité d'Admission",
        'model_info': "🤖 Modèle utilisé : {model} (R² = 79,83%)",
        'prediction_error': "❌ Erreur de prédiction : {e}",
        'prediction_hint': "💡 Assurez-vous que les valeurs saisies sont valides pour le modèle entraîné.",
        'factor_analysis': "📈 Analyse des Facteurs",
        'pdf_generation': "📄 Génération de PDF",
        'pdf_success': "✅ PDF généré avec succès !",
        'pdf_error': "❌ Erreur lors de la génération du PDF : {e}",
        'data_summary': "📋 Résumé des Données",
        'sidebar_info': "ℹ️ Informations sur le Modèle",
        'sidebar_model': "**Modèle:** {model}\n\n**R² Score:** 79,83%\n**Caractéristiques:** 19 variables\n\n**Meilleur modèle entraîné avec des données réelles**",
        'sidebar_report': "📄 Télécharger le Rapport d'Entraînement",
        'footer': "---",
        'language': "Langue",
        'spanish': "Espagnol",
        'english': "Anglais",
        'french': "Français",
        'german': "Allemand",
        'italian': "Italien",
        'portuguese': "Portugais",
        'russian': "Russe",
        'chinese': "Chinois",
        'japanese': "Japonais",
        'factor': 'Facteur',
        'value': "Valeur",
        'pdf_download': "Télécharger PDF",
        'form_instructions_title': '📝 Instructions',
        'form_instructions_body': 'Remplissez le formulaire avec les informations demandées pour obtenir une prédiction précise des performances académiques.',
        'form_basic_info': '📋 Informations de Base de l\'Étudiant',
        'form_school': '🏫 École',
        'form_school_help': 'École de l\'étudiant',
        'school_gp': 'Gabriel Pereira',
        'school_ms': 'Mousinho da Silveira',
        'form_sex': '👤 Sexe',
        'sex_f': 'Féminin',
        'sex_m': 'Masculin',
        'form_age': '🎂 Âge',
        'form_age_help': 'Âge actuel de l\'étudiant',
        'form_address': '🏠 Type d\'Adresse',
        'address_u': 'Urbaine',
        'address_r': 'Rurale',
        'form_medu': '👩‍🎓 Éducation de la Mère',
        'edu_0': 'Aucune',
        'edu_1': 'Primaire (4e année)',
        'edu_2': '5e à 9e année',
        'edu_3': 'Secondaire',
        'edu_4': 'Supérieure',
        'form_fedu': '👨‍🎓 Éducation du Père',
        'form_mjob': '👩‍💼 Travail de la Mère',
        'mjob_teacher': 'Enseignante',
        'mjob_health': 'Santé',
        'mjob_services': 'Services',
        'mjob_at_home': 'À la maison',
        'mjob_other': 'Autre',
        'form_reason': '🤔 Raison du choix de l\'école',
        'reason_home': 'Proche de la maison',
        'reason_reputation': 'Réputation de l\'école',
        'reason_course': 'Préférence de cours',
        'reason_other': 'Autre',
        'form_traveltime': '🚌 Temps de trajet à l\'école',
        'traveltime_1': '<15 min',
        'traveltime_2': '15-30 min',
        'traveltime_3': '30 min - 1 heure',
        'traveltime_4': '>1 heure',
        'form_academic_social_info': '📚 Informations Académiques et Sociales',
        'form_studytime': '⏱️ Temps d\'étude hebdomadaire',
        'studytime_1': '<2 heures',
        'studytime_2': '2-5 heures',
        'studytime_3': '5-10 heures',
        'studytime_4': '>10 heures',
        'form_failures': '❌ Échecs scolaires passés',
        'form_failures_help': 'Nombre d\'échecs scolaires passés',
        'form_higher': '🎓 Veut poursuivre des études supérieures ?',
        'yes': 'Oui',
        'no': 'Non',
        'form_internet': '🌐 Accès Internet à la maison',
        'form_dalc': '🍺 Consommation d\'alcool en semaine',
        'alc_1': 'Très faible',
        'alc_2': 'Faible',
        'alc_3': 'Moyenne',
        'alc_4': 'Élevée',
        'alc_5': 'Très élevée',
        'form_walc': '🍻 Consommation d\'alcool le week-end',
        'form_health': '🏥 État de santé actuel',
        'health_1': 'Très mauvais',
        'health_2': 'Mauvais',
        'health_3': 'Moyen',
        'health_4': 'Bon',
        'health_5': 'Très bon',
        'form_absences': '🚫 Nombre d\'absences scolaires',
        'form_absences_help': 'Nombre total d\'absences scolaires',
        'form_grades': '📊 Notes',
        'form_g1': '📈 Note 1ère Période (G1)',
        'form_g1_help': 'Note de la première période (0-20)',
        'form_g2': '📈 Note 2ème Période (G2)',
        'form_g2_help': 'Note de la deuxième période (0-20)',
        'g1_excellent': '✅ G1: Excellente note',
        'g1_average': '⚠️ G1: Note moyenne',
        'g1_low': '❌ G1: Note faible',
        'g2_excellent': '✅ G2: Excellente note',
        'g2_average': '⚠️ G2: Note moyenne',
        'g2_low': '❌ G2: Note faible',
        'form_ready': '✨ Prêt à voir le résultat ?',
        'predict_button_final': '🔮 Prédire la Probabilité d\'Admission',
        'pdf_button_report': '📄 Générer un Rapport PDF',
        'factor_higher_yes': '✅ Intérêt pour les études supérieures',
        'factor_failures_no': '✅ Aucun échec scolaire passé',
        'factor_failures_many': '❌ Plusieurs échecs scolaires',
        'factor_good_studytime': '✅ Bon temps d\'étude',
        'factor_internet_yes': '✅ Accès Internet',
        'typical_age': '✅ Âge dans la plage attendue'
    },
    'de': {  # German
        'main_title': "🎓 Universitätszulassungs-Vorhersage",
        'subtitle': "**Vorhersagesystem basierend auf maschinellem Lernen**",
        'student_info': "📋 Studenteninformationen",
        'predict_button': "🔮 Zulassung Vorhersagen",
        'pdf_button': "📄 PDF Generieren",
        'error_found': "❌ Folgende Fehler wurden gefunden:",
        'complete_fields': "❌ Bitte alle Pflichtfelder ausfüllen",
        'success_data': "✅ Daten erfolgreich verarbeitet!",
        'prediction_result': "🔮 Vorhersageergebnis",
        'likely_admission': "🎉 **WAHRSCHEINLICHE ZULASSUNG**",
        'unlikely_admission': "❌ **UNWAHRSCHEINLICHE ZULASSUNG**",
        'admission_probability': "Zulassungswahrscheinlichkeit",
        'model_info': "🤖 Verwendetes Modell: {model} (R² = 79,83%)",
        'prediction_error': "❌ Vorhersagefehler: {e}",
        'prediction_hint': "💡 Stellen Sie sicher, dass die eingegebenen Werte für das trainierte Modell gültig sind.",
        'factor_analysis': "📈 Faktoranalyse",
        'pdf_generation': "📄 PDF-Generierung",
        'pdf_success': "✅ PDF erfolgreich generiert!",
        'pdf_error': "❌ Fehler beim Generieren des PDFs: {e}",
        'data_summary': "📋 Datenzusammenfassung",
        'sidebar_info': "ℹ️ Modellinformationen",
        'sidebar_model': "**Modell:** {model}\n\n**R² Score:** 79,83%\n**Merkmale:** 19 Variablen\n\n**Bestes Modell mit echten Daten trainiert**",
        'sidebar_report': "📄 Trainingsbericht Herunterladen",
        'footer': "---",
        'language': "Sprache",
        'spanish': "Spanisch",
        'english': "Englisch",
        'french': "Französisch",
        'german': "Deutsch",
        'value': "Wert",
        'factor': 'Faktor',
        'pdf_download': "PDF Herunterladen",
        'form_instructions_title': '📝 Anweisungen',
        'form_instructions_body': 'Füllen Sie das Formular mit den angeforderten Informationen aus, um eine genaue Vorhersage der akademischen Leistung zu erhalten.',
        'form_basic_info': '📋 Grundlegende Studenteninformationen',
        'form_school': '🏫 Schule',
        'form_school_help': 'Schule des Studenten',
        'school_gp': 'Gabriel Pereira',
        'school_ms': 'Mousinho da Silveira',
        'form_sex': '👤 Geschlecht',
        'sex_f': 'Weiblich',
        'sex_m': 'Männlich',
        'form_age': '🎂 Alter',
        'form_age_help': 'Aktuelles Alter des Studenten',
        'form_address': '🏠 Adresstyp',
        'address_u': 'Städtisch',
        'address_r': 'Ländlich',
        'form_medu': '👩‍🎓 Bildung der Mutter',
        'edu_0': 'Keine',
        'edu_1': 'Grundschule (4. Klasse)',
        'edu_2': '5. bis 9. Klasse',
        'edu_3': 'Sekundarschulbildung',
        'edu_4': 'Hochschulbildung',
        'form_fedu': '👨‍🎓 Bildung des Vaters',
        'form_mjob': '👩‍💼 Beruf der Mutter',
        'mjob_teacher': 'Lehrerin',
        'mjob_health': 'Gesundheit',
        'mjob_services': 'Dienstleistungen',
        'mjob_at_home': 'Zu Hause',
        'mjob_other': 'Andere',
        'form_reason': '🤔 Grund für die Schulwahl',
        'reason_home': 'In der Nähe von zu Hause',
        'reason_reputation': 'Ruf der Schule',
        'reason_course': 'Kurspräferenz',
        'reason_other': 'Andere',
        'form_traveltime': '🚌 Reisezeit zur Schule',
        'traveltime_1': '<15 min',
        'traveltime_2': '15-30 min',
        'traveltime_3': '30 min - 1 Stunde',
        'traveltime_4': '>1 Stunde',
        'form_academic_social_info': '📚 Akademische und soziale Informationen',
        'form_studytime': '⏱️ Wöchentliche Lernzeit',
        'studytime_1': '<2 Stunden',
        'studytime_2': '2-5 Stunden',
        'studytime_3': '5-10 Stunden',
        'studytime_4': '>10 Stunden',
        'form_failures': '❌ Frühere Klassenfehler',
        'form_failures_help': 'Anzahl der früheren Klassenfehler',
        'form_higher': '🎓 Möchte eine höhere Ausbildung absolvieren?',
        'yes': 'Ja',
        'no': 'Nein',
        'form_internet': '🌐 Internetzugang zu Hause',
        'form_dalc': '🍺 Alkoholkonsum an Arbeitstagen',
        'alc_1': 'Sehr niedrig',
        'alc_2': 'Niedrig',
        'alc_3': 'Mittel',
        'alc_4': 'Hoch',
        'alc_5': 'Sehr hoch',
        'form_walc': '🍻 Alkoholkonsum am Wochenende',
        'form_health': '🏥 Aktueller Gesundheitszustand',
        'health_1': 'Sehr schlecht',
        'health_2': 'Schlecht',
        'health_3': 'Durchschnittlich',
        'health_4': 'Gut',
        'health_5': 'Sehr gut',
        'form_absences': '🚫 Anzahl der Schulabsenzen',
        'form_absences_help': 'Gesamtzahl der Schulabsenzen',
        'form_grades': '📊 Noten',
        'form_g1': '📈 Note des ersten Zeitraums (G1)',
        'form_g1_help': 'Note für den ersten Zeitraum (0-20)',
        'form_g2': '📈 Note des zweiten Zeitraums (G2)',
        'form_g2_help': 'Note für den zweiten Zeitraum (0-20)',
        'g1_excellent': '✅ G1: Ausgezeichnete Note',
        'g1_average': '⚠️ G1: Durchschnittsnote',
        'g1_low': '❌ G1: Schlechte Note',
        'g2_excellent': '✅ G2: Ausgezeichnete Note',
        'g2_average': '⚠️ G2: Durchschnittsnote',
        'g2_low': '❌ G2: Schlechte Note',
        'form_ready': '✨ Bereit, das Ergebnis zu sehen?',
        'predict_button_final': '🔮 Zulassungswahrscheinlichkeit vorhersagen',
        'pdf_button_report': '📄 PDF-Bericht erstellen',
        'factor_higher_yes': '✅ Interesse an höherer Bildung',
        'factor_failures_no': '✅ Keine früheren Klassenfehler',
        'factor_failures_many': '❌ Mehrere Klassenfehler',
        'factor_good_studytime': '✅ Gute Lernzeit',
        'factor_internet_yes': '✅ Internetzugang',
        'typical_age': '✅ Alter im erwarteten Bereich'
    },
    'it': {  # Italian
        'main_title': "🎓 Predittore di Ammissione Universitaria",
        'subtitle': "**Sistema di predizione basato su Machine Learning**",
        'student_info': "📋 Informazioni Studente",
        'predict_button': "🔮 Predici Ammissione",
        'pdf_button': "📄 Genera PDF",
        'error_found': "❌ Sono stati trovati i seguenti errori:",
        'complete_fields': "❌ Per favore completa tutti i campi obbligatori",
        'success_data': "✅ Dati elaborati con successo!",
        'prediction_result': "🔮 Risultato della Predizione",
        'likely_admission': "🎉 **AMMISSIONE PROBABILE**",
        'unlikely_admission': "❌ **AMMISSIONE IMPROBABILE**",
        'admission_probability': "Probabilità di Ammissione",
        'model_info': "🤖 Modello utilizzato: {model} (R² = 79,83%)",
        'prediction_error': "❌ Errore di predizione: {e}",
        'prediction_hint': "💡 Assicurati che i valori inseriti siano validi per il modello addestrato.",
        'factor_analysis': "📈 Analisi dei Fattori",
        'pdf_generation': "📄 Generazione PDF",
        'pdf_success': "✅ PDF generato con successo!",
        'pdf_error': "❌ Errore nella generazione del PDF: {e}",
        'data_summary': "📋 Riassunto Dati",
        'sidebar_info': "ℹ️ Informazioni sul Modello",
        'sidebar_model': "**Modello:** {model}\n\n**R² Score:** 79,83%\n**Caratteristiche:** 19 variabili\n\n**Miglior modello addestrato con dati reali**",
        'sidebar_report': "📄 Scarica Rapporto di Addestramento",
        'footer': "---",
        'language': "Lingua",
        'spanish': "Spagnolo",
        'english': "Inglese",
        'french': "Francese",
        'german': "Tedesco",
        'italian': "Italiano",
        'factor': 'Fattore',
        'value': "Valore",
        'pdf_download': "Scarica PDF",
        'form_instructions_title': '📝 Istruzioni',
        'form_instructions_body': 'Compila il modulo con le informazioni richieste per ottenere una previsione accurata delle prestazioni accademiche.',
        'form_basic_info': '📋 Informazioni di Base dello Studente',
        'form_school': '🏫 Scuola',
        'form_school_help': 'Scuola dello studente',
        'school_gp': 'Gabriel Pereira',
        'school_ms': 'Mousinho da Silveira',
        'form_sex': '👤 Sesso',
        'sex_f': 'Femmina',
        'sex_m': 'Maschio',
        'form_age': '🎂 Età',
        'form_age_help': 'Età attuale dello studente',
        'form_address': '🏠 Tipo di Indirizzo',
        'address_u': 'Urbano',
        'address_r': 'Rurale',
        'form_medu': '👩‍🎓 Istruzione della Madre',
        'edu_0': 'Nessuna',
        'edu_1': 'Istruzione primaria (4ª elementare)',
        'edu_2': 'Dalla 5ª alla 9ª elementare',
        'edu_3': 'Istruzione secondaria',
        'edu_4': 'Istruzione superiore',
        'form_fedu': '👨‍🎓 Istruzione del Padre',
        'form_mjob': '👩‍💼 Lavoro della Madre',
        'mjob_teacher': 'Insegnante',
        'mjob_health': 'Salute',
        'mjob_services': 'Servizi',
        'mjob_at_home': 'A casa',
        'mjob_other': 'Altro',
        'form_reason': '🤔 Motivo della scelta della scuola',
        'reason_home': 'Vicino a casa',
        'reason_reputation': 'Reputazione della scuola',
        'reason_course': 'Preferenza del corso',
        'reason_other': 'Altro',
        'form_traveltime': '🚌 Tempo di viaggio per la scuola',
        'traveltime_1': '<15 min',
        'traveltime_2': '15-30 min',
        'traveltime_3': '30 min - 1 ora',
        'traveltime_4': '>1 ora',
        'form_academic_social_info': '📚 Informazioni Accademiche e Sociali',
        'form_studytime': '⏱️ Tempo di studio settimanale',
        'studytime_1': '<2 ore',
        'studytime_2': '2-5 ore',
        'studytime_3': '5-10 ore',
        'studytime_4': '>10 ore',
        'form_failures': '❌ Fallimenti scolastici passati',
        'form_failures_help': 'Numero di fallimenti scolastici passati',
        'form_higher': '🎓 Vuole proseguire gli studi superiori?',
        'yes': 'Sì',
        'no': 'No',
        'form_internet': '🌐 Accesso a Internet a casa',
        'form_dalc': '🍺 Consumo di alcol durante la settimana',
        'alc_1': 'Molto basso',
        'alc_2': 'Basso',
        'alc_3': 'Medio',
        'alc_4': 'Alto',
        'alc_5': 'Molto alto',
        'form_walc': '🍻 Consumo di alcol nel fine settimana',
        'form_health': '🏥 Stato di salute attuale',
        'health_1': 'Molto cattivo',
        'health_2': 'Cattivo',
        'health_3': 'Medio',
        'health_4': 'Buono',
        'health_5': 'Molto buono',
        'form_absences': '🚫 Numero di assenze scolastiche',
        'form_absences_help': 'Numero totale di assenze scolastiche',
        'form_grades': '📊 Voti',
        'form_g1': '📈 Voto 1° Periodo (G1)',
        'form_g1_help': 'Voto del primo periodo (0-20)',
        'form_g2': '📈 Voto 2° Periodo (G2)',
        'form_g2_help': 'Voto del secondo periodo (0-20)',
        'g1_excellent': '✅ G1: Voto eccellente',
        'g1_average': '⚠️ G1: Voto medio',
        'g1_low': '❌ G1: Voto basso',
        'g2_excellent': '✅ G2: Voto eccellente',
        'g2_average': '⚠️ G2: Voto medio',
        'g2_low': '❌ G2: Voto basso',
        'form_ready': '✨ Pronto a vedere il risultato?',
        'predict_button_final': '🔮 Predici Probabilità di Ammissione',
        'pdf_button_report': '📄 Genera Rapporto PDF',
        'factor_higher_yes': '✅ Interesse per l\'istruzione superiore',
        'factor_failures_no': '✅ Nessun fallimento scolastico passato',
        'factor_failures_many': '❌ Molteplici fallimenti scolastici',
        'factor_good_studytime': '✅ Buon tempo di studio',
        'factor_internet_yes': '✅ Accesso a Internet',
        'typical_age': '✅ Età compresa nell\'intervallo previsto'
    },
    'pt': {  # Portuguese
        'main_title': "🎓 Preditor de Admissão Universitária",
        'subtitle': "**Sistema de predição baseado em Machine Learning**",
        'student_info': "📋 Informações do Estudante",
        'predict_button': "🔮 Predizer Admissão",
        'pdf_button': "📄 Gerar PDF",
        'error_found': "❌ Os seguintes erros foram encontrados:",
        'complete_fields': "❌ Por favor, preencha todos os campos obrigatórios",
        'success_data': "✅ Dados processados com sucesso!",
        'prediction_result': "🔮 Resultado da Predição",
        'likely_admission': "🎉 **ADMISSÃO PROVÁVEL**",
        'unlikely_admission': "❌ **ADMISSÃO IMPROVÁVEL**",
        'admission_probability': "Probabilidade de Admissão",
        'model_info': "🤖 Modelo utilizado: {model} (R² = 79,83%)",
        'prediction_error': "❌ Erro de predição: {e}",
        'prediction_hint': "💡 Certifique-se de que os valores inseridos sejam válidos para o modelo treinado.",
        'factor_analysis': "📈 Análise de Fatores",
        'pdf_generation': "📄 Geração de PDF",
        'pdf_success': "✅ PDF gerado com sucesso!",
        'pdf_error': "❌ Erro ao gerar PDF: {e}",
        'data_summary': "📋 Resumo dos Dados",
        'sidebar_info': "ℹ️ Informações do Modelo",
        'sidebar_model': "**Modello:** {model}\n\n**R² Score:** 79,83%\n**Características:** 19 variáveis\n\n**Melhor modelo treinado com dados reais**",
        'sidebar_report': "📄 Baixar Relatório de Treinamento",
        'footer': "---",
        'language': "Idioma",
        'spanish': "Espanhol",
        'english': "Inglês",
        'french': "Francês",
        'german': "Alemão",
        'italian': "Italiano",
        'portuguese': "Português",
        'factor': 'Fator',
        'value': "Valor",
        'pdf_download': "Baixar PDF",
        'form_instructions_title': '📝 Instruções',
        'form_instructions_body': 'Preencha o formulário com as informações solicitadas para obter uma previsão precisa do desempenho acadêmico.',
        'form_basic_info': '📋 Informações Básicas do Estudante',
        'form_school': '🏫 Escola',
        'form_school_help': 'Escola do estudante',
        'school_gp': 'Gabriel Pereira',
        'school_ms': 'Mousinho da Silveira',
        'form_sex': '👤 Sexo',
        'sex_f': 'Feminino',
        'sex_m': 'Masculino',
        'form_age': '🎂 Idade',
        'form_age_help': 'Idade atual do estudante',
        'form_address': '🏠 Tipo de Endereço',
        'address_u': 'Urbano',
        'address_r': 'Rural',
        'form_medu': '👩‍🎓 Educação da Mãe',
        'edu_0': 'Nenhuma',
        'edu_1': 'Ensino fundamental (4ª série)',
        'edu_2': '5ª a 9ª série',
        'edu_3': 'Ensino médio',
        'edu_4': 'Ensino superior',
        'form_fedu': '👨‍🎓 Educação do Pai',
        'form_mjob': '👩‍💼 Trabalho da Mãe',
        'mjob_teacher': 'Professora',
        'mjob_health': 'Saúde',
        'mjob_services': 'Serviços',
        'mjob_at_home': 'Em casa',
        'mjob_other': 'Outro',
        'form_reason': '🤔 Razão para escolher a escola',
        'reason_home': 'Perto de casa',
        'reason_reputation': 'Reputação da escola',
        'reason_course': 'Preferência do curso',
        'reason_other': 'Outro',
        'form_traveltime': '🚌 Tempo de viagem para a escola',
        'traveltime_1': '<15 min',
        'traveltime_2': '15-30 min',
        'traveltime_3': '30 min - 1 hora',
        'traveltime_4': '>1 hora',
        'form_academic_social_info': '📚 Informações Acadêmicas e Sociais',
        'form_studytime': '⏱️ Tempo de estudo semanal',
        'studytime_1': '<2 horas',
        'studytime_2': '2-5 horas',
        'studytime_3': '5-10 horas',
        'studytime_4': '>10 horas',
        'form_failures': '❌ Falhas de classe anteriores',
        'form_failures_help': 'Número de falhas de classe anteriores',
        'form_higher': '🎓 Deseja cursar ensino superior?',
        'yes': 'Sim',
        'no': 'Não',
        'form_internet': '🌐 Acesso à Internet em casa',
        'form_dalc': '🍺 Consumo de álcool durante a semana',
        'alc_1': 'Muito baixo',
        'alc_2': 'Baixo',
        'alc_3': 'Médio',
        'alc_4': 'Alto',
        'alc_5': 'Muito alto',
        'form_walc': '🍻 Consumo de álcool no fim de semana',
        'form_health': '🏥 Estado de saúde atual',
        'health_1': 'Muito ruim',
        'health_2': 'Ruim',
        'health_3': 'Médio',
        'health_4': 'Bom',
        'health_5': 'Muito bom',
        'form_absences': '🚫 Número de faltas escolares',
        'form_absences_help': 'Número total de faltas escolares',
        'form_grades': '📊 Notas',
        'form_g1': '📈 Nota do 1º Período (G1)',
        'form_g1_help': 'Nota do primeiro período (0-20)',
        'form_g2': '📈 Nota do 2º Período (G2)',
        'form_g2_help': 'Nota do segundo período (0-20)',
        'g1_excellent': '✅ G1: Nota excelente',
        'g1_average': '⚠️ G1: Nota média',
        'g1_low': '❌ G1: Nota baixa',
        'g2_excellent': '✅ G2: Nota excelente',
        'g2_average': '⚠️ G2: Nota média',
        'g2_low': '❌ G2: Nota baixa',
        'form_ready': '✨ Pronto para ver o resultado?',
        'predict_button_final': '🔮 Prever Probabilidade de Admissão',
        'pdf_button_report': '📄 Gerar Relatório PDF',
        'factor_higher_yes': '✅ Interesse em ensino superior',
        'factor_failures_no': '✅ Sem falhas de classe anteriores',
        'factor_failures_many': '❌ Múltiplas falhas de classe',
        'factor_good_studytime': '✅ Bom tempo de estudo',
        'factor_internet_yes': '✅ Acesso à Internet',
        'typical_age': '✅ Idade dentro da faixa esperada'
    },
    'ru': {  # Russian
        'main_title': "🎓 Предсказатель Поступления в Университет",
        'factor_internet_yes': '✅ Доступ к интернету',
        'subtitle': "**Система предсказания на основе машинного обучения**",
        'student_info': "📋 Информация о Студенте",
        'predict_button': "🔮 Предсказать Поступление",
        'pdf_button': "📄 Создать PDF",
        'error_found': "❌ Найдены следующие ошибки:",
        'complete_fields': "❌ Пожалуйста, заполните все обязательные поля",
        'success_data': "✅ Данные успешно обработаны!",
        'prediction_result': "🔮 Результат Предсказания",
        'likely_admission': "🎉 **ВЕРОЯТНОЕ ПОСТУПЛЕНИЕ**",
        'unlikely_admission': "❌ **МАЛОВЕРОЯТНОЕ ПОСТУПЛЕНИЕ**",
        'admission_probability': "Вероятность Поступления",
        'model_info': "🤖 Используемая модель: {model} (R² = 79,83%)",
        'prediction_error': "❌ Ошибка предсказания: {e}",
        'prediction_hint': "💡 Убедитесь, что введенные значения действительны для обученной модели.",
        'factor_analysis': "📈 Анализ Факторов",
        'pdf_generation': "📄 Создание PDF",
        'pdf_success': "✅ PDF успешно создан!",
        'pdf_error': "❌ Ошибка при создании PDF: {e}",
        'data_summary': "📋 Сводка Данных",
        'sidebar_info': "ℹ️ Информация о Модели",
        'sidebar_model': "**Модель:** {model}\n\n**R² Score:** 79,83%\n**Особенности:** 19 переменных\n\n**Лучшая модель, обученная на реальных данных**",
        'sidebar_report': "📄 Скачать Отчет о Обучении",
        'footer': "---",
        'language': "Язык",
        'spanish': "Испанский",
        'english': "Английский",
        'french': "Французский",
        'german': "Немецкий",
        'italian': "Итальянский",
        'portuguese': "Португальский",
        'russian': "Русский",
        'factor': 'Фактор',
        'value': "Значение",
        'pdf_download': "Скачать PDF",
        'form_instructions_title': '📝 Инструкции',
        'form_instructions_body': 'Заполните форму с запрашиваемой информацией, чтобы получить точный прогноз успеваемости.',
        'form_basic_info': '📋 Основная информация о студенте',
        'form_school': '🏫 Школа',
        'form_school_help': 'Школа студента',
        'school_gp': 'Габриэль Перейра',
        'school_ms': 'Моусиньо да Силвейра',
        'form_sex': '👤 Пол',
        'sex_f': 'Женский',
        'sex_m': 'Мужской',
        'form_age': '🎂 Возраст',
        'form_age_help': 'Текущий возраст студента',
        'form_address': '🏠 Тип адреса',
        'address_u': 'Городской',
        'address_r': 'Сельский',
        'form_medu': '👩‍🎓 Образование матери',
        'edu_0': 'Нет',
        'edu_1': 'Начальное образование (4-й класс)',
        'edu_2': '5-9 классы',
        'edu_3': 'Среднее образование',
        'edu_4': 'Высшее образование',
        'form_fedu': '👨‍🎓 Образование отца',
        'form_mjob': '👩‍💼 Работа матери',
        'mjob_teacher': 'Учитель',
        'mjob_health': 'Здравоохранение',
        'mjob_services': 'Услуги',
        'mjob_at_home': 'Дома',
        'mjob_other': 'Другое',
        'form_reason': '🤔 Причина выбора школы',
        'reason_home': 'Близко к дому',
        'reason_reputation': 'Репутация школы',
        'reason_course': 'Предпочтение курса',
        'reason_other': 'Другое',
        'form_traveltime': '🚌 Время в пути до школы',
        'traveltime_1': '<15 мин',
        'traveltime_2': '15-30 мин',
        'traveltime_3': '30 мин - 1 час',
        'traveltime_4': '>1 часа',
        'form_academic_social_info': '📚 Академическая и социальная информация',
        'form_studytime': '⏱️ Еженедельное учебное время',
        'studytime_1': '<2 часов',
        'studytime_2': '2-5 часов',
        'studytime_3': '5-10 часов',
        'studytime_4': '>10 часов',
        'form_failures': '❌ Прошлые неудачи в классе',
        'form_failures_help': 'Количество прошлых неудач в классе',
        'form_higher': '🎓 Хочет получить высшее образование?',
        'yes': 'Да',
        'no': 'Нет',
        'form_internet': '🌐 Доступ в Интернет дома',
        'form_dalc': '🍺 Потребление алкоголя в будние дни',
        'alc_1': 'Очень низкое',
        'alc_2': 'Низкое',
        'alc_3': 'Среднее',
        'alc_4': 'Высокое',
        'alc_5': 'Очень высокое',
        'form_walc': '🍻 Потребление алкоголя в выходные дни',
        'form_health': '🏥 Текущее состояние здоровья',
        'health_1': 'Очень плохое',
        'health_2': 'Плохое',
        'health_3': 'Среднее',
        'health_4': 'Хорошее',
        'health_5': 'Очень хорошее',
        'form_absences': '🚫 Количество пропусков занятий',
        'form_absences_help': 'Общее количество пропусков занятий',
        'form_grades': '📊 Оценки',
        'form_g1': '📈 Оценка за первый период (G1)',
        'form_g1_help': 'Оценка за первый период (0-20)',
        'form_g2': '📈 Оценка за второй период (G2)',
        'form_g2_help': 'Оценка за второй период (0-20)',
        'g1_excellent': '✅ G1: Отличная оценка',
        'g1_average': '⚠️ G1: Средняя оценка',
        'g1_low': '❌ G1: Низкая оценка',
        'g2_excellent': '✅ G2: Отличная оценка',
        'g2_average': '⚠️ G2: Средняя оценка',
        'g2_low': '❌ G2: Низкая оценка',
        'form_ready': '✨ Готовы увидеть результат?',
        'predict_button_final': '🔮 Предсказать вероятность поступления',
        'pdf_button_report': '📄 Создать PDF-отчет',
        'typical_age': '✅ Возраст в пределах ожидаемого диапазона',
        'factor_higher_yes': '✅ Интерес к высшему образованию',
        'factor_failures_no': '✅ Нет прошлых неуспешных оценок'
    },
    'zh': {  # Chinese
        'main_title': "🎓 大学录取预测器",
        'subtitle': "**基于机器学习的预测系统**",
        'student_info': "📋 学生信息",
        'predict_button': "🔮 预测录取",
        'pdf_button': "📄 生成PDF",
        'error_found': "❌ 发现以下错误：",
        'complete_fields': "❌ 请填写所有必填字段",
        'factor_internet_yes': '✅ 有互联网连接',
        'success_data': "✅ 数据处理成功！",
        'prediction_result': "🔮 预测结果",
        'likely_admission': "🎉 **可能录取**",
        'unlikely_admission': "❌ **不太可能录取**",
        'admission_probability': "录取概率",
        'model_info': "🤖 使用的模型：{model} (R² = 79.83%)",
        'prediction_error': "❌ 预测错误：{e}",
        'prediction_hint': "💡 确保输入的值对训练模型有效。",
        'factor_analysis': "📈 因子分析",
        'pdf_generation': "📄 PDF生成",
        'pdf_success': "✅ PDF生成成功！",
        'pdf_error': "❌ 生成PDF错误：{e}",
        'data_summary': "📋 数据摘要",
        'sidebar_info': "ℹ️ 模型信息",
        'sidebar_model': "**模型：** {model}\n\n**R² 分数：** 79.83%\n**特征：** 19个变量\n\n**用真实数据训练的最佳模型**",
        'sidebar_report': "📄 下载训练报告",
        'footer': "---",
        'language': "语言",
        'spanish': "西班牙语",
        'english': "英语",
        'french': "法语",
        'german': "德语",
        'italian': "意大利语",
        'portuguese': "葡萄牙语",
        'russian': "俄语",
        'chinese': "中文",
        'factor': '因素',
        'value': "值",
        'pdf_download': "下载PDF",
        'form_instructions_title': '📝 说明',
        'form_instructions_body': '请填写表格并提供所需信息，以获得对学业成绩的准确预测。',
        'form_basic_info': '📋 学生基本信息',
        'form_school': '🏫 学校',
        'form_school_help': '学生的学校',
        'school_gp': '加布里埃尔·佩雷拉',
        'school_ms': '穆西尼奥·达·西尔维拉',
        'form_sex': '👤 性别',
        'sex_f': '女',
        'sex_m': '男',
        'form_age': '🎂 年龄',
        'form_age_help': '学生的当前年龄',
        'form_address': '🏠 地址类型',
        'address_u': '城市',
        'address_r': '农村',
        'form_medu': '👩‍🎓 母亲的教育',
        'edu_0': '无',
        'edu_1': '小学（四年级）',
        'edu_2': '五至九年级',
        'edu_3': '中学教育',
        'edu_4': '高等教育',
        'form_fedu': '👨‍🎓 父亲的教育',
        'form_mjob': '👩‍💼 母亲的工作',
        'mjob_teacher': '教师',
        'mjob_health': '健康',
        'mjob_services': '服务',
        'mjob_at_home': '在家',
        'mjob_other': '其他',
        'form_reason': '🤔 选择学校的原因',
        'reason_home': '离家近',
        'reason_reputation': '学校声誉',
        'reason_course': '课程偏好',
        'reason_other': '其他',
        'form_traveltime': '🚌 上学时间',
        'traveltime_1': '<15分钟',
        'traveltime_2': '15-30分钟',
        'traveltime_3': '30分钟 - 1小时',
        'traveltime_4': '>1小时',
        'form_academic_social_info': '📚 学术和社交信息',
        'form_studytime': '⏱️ 每周学习时间',
        'studytime_1': '<2小时',
        'studytime_2': '2-5小时',
        'studytime_3': '5-10小时',
        'studytime_4': '>10小时',
        'form_failures': '❌ 过去的课程失败',
        'form_failures_help': '过去的课程失败次数',
        'form_higher': '🎓 是否希望接受高等教育？',
        'yes': '是',
        'no': '否',
        'form_internet': '🌐 家中是否有互联网',
        'form_dalc': '🍺 工作日饮酒情况',
        'alc_1': '非常低',
        'alc_2': '低',
        'alc_3': '中',
        'alc_4': '高',
        'alc_5': '非常高',
        'form_walc': '🍻 周末饮酒情况',
        'form_health': '🏥 当前健康状况',
        'health_1': '非常差',
        'health_2': '差',
        'health_3': '一般',
        'health_4': '好',
        'health_5': '非常好',
        'form_absences': '🚫 缺勤次数',
        'form_absences_help': '总缺勤次数',
        'form_grades': '📊 成绩',
        'form_g1': '📈 第一学期成绩 (G1)',
        'form_g1_help': '第一学期成绩 (0-20)',
        'form_g2': '📈 第二学期成绩 (G2)',
        'form_g2_help': '第二学期成绩 (0-20)',
        'g1_excellent': '✅ G1: 优秀成绩',
        'g1_average': '⚠️ G1: 平均成绩',
        'g1_low': '❌ G1: 低分',
        'g2_excellent': '✅ G2: 优秀成绩',
        'g2_average': '⚠️ G2: 平均成绩',
        'g2_low': '❌ G2: 低分',
        'factor_failures_no': '✅ 没有过往的课程不及格记录',
        'form_ready': '✨ 准备好查看结果了吗？',
        'predict_button_final': '🔮 预测录取概率',
        'pdf_button_report': '📄 生成PDF报告',
        'typical_age': '✅ 年龄在预期范围内',
        'factor_higher_yes': '✅ 对高等教育感兴趣'
    },
    'ja': {  # Japanese
        'main_title': "🎓 大学入学予測システム",
        'factor_failures_no': '✅ 過去の落第はありません',
        'subtitle': "**機械学習による予測システム**",
        'factor_internet_yes': '✅ インターネット接続あり',
        'student_info': "📋 学生情報",
        'predict_button': "🔮 入学予測",
        'pdf_button': "📄 PDF生成",
        'error_found': "❌ 次のエラーが見つかりました：",
        'complete_fields': "❌ すべての必須フィールドを完成してください",
        'success_data': "✅ データが正常に処理されました！",
        'prediction_result': "🔮 予測結果",
        'likely_admission': "🎉 **入学可能性高い**",
        'unlikely_admission': "❌ **入学可能性低い**",
        'admission_probability': "入学確率",
        'model_info': "🤖 使用モデル：{model} (R² = 79.83%)",
        'prediction_error': "❌ 予測エラー：{e}",
        'prediction_hint': "💡 入力値が訓練されたモデルに有効であることを確認してください。",
        'factor_analysis': "📈 要因分析",
        'pdf_generation': "📄 PDF生成",
        'pdf_success': "✅ PDFが正常に生成されました！",
        'pdf_error': "❌ PDF生成エラー：{e}",
        'data_summary': "📋 データ概要",
        'sidebar_info': "ℹ️ モデル情報",
        'sidebar_model': "**モデル：** {model}\n\n**R² スコア：** 79.83%\n**特徴：** 19変数\n\n**実データで訓練された最良のモデル**",
        'sidebar_report': "📄 訓練レポートをダウンロード",
        'footer': "---",
        'language': "言語",
        'spanish': "スペイン語",
        'english': "英語",
        'french': "フランス語",
        'german': "ドイツ語",
        'italian': "イタリア語",
        'portuguese': "ポルトガル語",
        'russian': "ロシア語",
        'chinese': "中国語",
        'japanese': "日本語",
        'factor': '要因',
        'value': "値",
        'pdf_download': "PDFダウンロード",
        'form_instructions_title': '📝 手順',
        'form_instructions_body': '要求された情報をフォームに記入して、学業成績の正確な予測を取得します。',
        'form_basic_info': '📋 学生基本情報',
        'form_school': '🏫 学校',
        'form_school_help': '学生の学校',
        'school_gp': 'ガブリエル・ペレイラ',
        'school_ms': 'モウシーニョ・ダ・シルヴェイラ',
        'form_sex': '👤 性別',
        'sex_f': '女性',
        'sex_m': '男性',
        'form_age': '🎂 年齢',
        'form_age_help': '学生の現在の年齢',
        'form_address': '🏠 住所タイプ',
        'address_u': '都市部',
        'address_r': '地方',
        'form_medu': '👩‍🎓 母親の学歴',
        'edu_0': 'なし',
        'edu_1': '初等教育（4年生）',
        'edu_2': '5年生から9年生',
        'edu_3': '中等教育',
        'edu_4': '高等教育',
        'form_fedu': '👨‍🎓 父親の学歴',
        'form_mjob': '👩‍💼 母親の仕事',
        'mjob_teacher': '教師',
        'mjob_health': '健康',
        'mjob_services': 'サービス',
        'mjob_at_home': '在宅',
        'mjob_other': 'その他',
        'form_reason': '🤔 学校を選んだ理由',
        'reason_home': '家から近い',
        'reason_reputation': '学校の評判',
        'reason_course': 'コースの好み',
        'reason_other': 'その他',
        'form_traveltime': '🚌 通学時間',
        'traveltime_1': '<15分',
        'traveltime_2': '15-30分',
        'traveltime_3': '30分 - 1時間',
        'traveltime_4': '>1時間',
        'form_academic_social_info': '📚 学業および社会情報',
        'form_studytime': '⏱️ 週間学習時間',
        'studytime_1': '<2時間',
        'studytime_2': '2-5時間',
        'studytime_3': '5-10時間',
        'studytime_4': '>10時間',
        'form_failures': '❌ 過去の授業の失敗',
        'form_failures_help': '過去の授業の失敗回数',
        'form_higher': '🎓 高等教育を受けたいですか？',
        'yes': 'はい',
        'no': 'いいえ',
        'form_internet': '🌐 自宅でのインターネットアクセス',
        'form_dalc': '🍺 平日のアルコール消費量',
        'alc_1': '非常に低い',
        'alc_2': '低い',
        'alc_3': '普通',
        'alc_4': '高い',
        'alc_5': '非常に高い',
        'form_walc': '🍻 週末のアルコール消費量',
        'form_health': '🏥 現在の健康状態',
        'health_1': '非常に悪い',
        'health_2': '悪い',
        'health_3': '普通',
        'health_4': '良い',
        'health_5': '非常に良い',
        'form_absences': '🚫 学校の欠席日数',
        'form_absences_help': '総欠席日数',
        'form_grades': '📊 成績',
        'form_g1': '📈 第1期成績 (G1)',
        'form_g1_help': '第1期の成績 (0-20)',
        'form_g2': '📈 第2期成績 (G2)',
        'form_g2_help': '第2期の成績 (0-20)',
        'g1_excellent': '✅ G1: 優秀な成績',
        'g1_average': '⚠️ G1: 平均的な成績',
        'g1_low': '❌ G1: 低い成績',
        'g2_excellent': '✅ G2: 優秀な成績',
        'g2_average': '⚠️ G2: 平均的な成績',
        'g2_low': '❌ G2: 低い成績',
        'form_ready': '✨ 結果を見る準備はできましたか？',
        'predict_button_final': '🔮 入学確率を予測する',
        'pdf_button_report': '📄 PDFレポートを生成する',
        'typical_age': '✅ 年齢が期待範囲内です',
        'factor_higher_yes': '✅ 高等教育への関心'
    }
}

def get_all_supported_languages():
    """Returns all language codes that are supported"""
    return ['es', 'en', 'fr', 'de', 'it', 'pt', 'ru', 'zh', 'ja']

def get_language_name(lang_code):
    """Returns the native name of a language given its code"""
    lang_names = {
        'es': 'Español',
        'en': 'English',
        'fr': 'Français',
        'de': 'Deutsch',
        'it': 'Italiano',
        'pt': 'Português',
        'ru': 'Русский',
        'zh': '中文',
        'ja': '日本語'
    }
    return lang_names.get(lang_code, lang_code)