# Additional languages for multilingual support

additional_languages = {
    'fr': {  # French
        'main_title': "🎓 Prédicteur d'Admission Universitaire",
        'subtitle': "**Système de prédiction basé sur l'apprentissage automatique**",
        'student_info': "📋 Informations Étudiant",
        'year_of_birth': "Année de Naissance",
        'sex': "Sexe",
        'sexs': ['Masculin', 'Féminin'],
        'school_name': "Nom de l'école",
        'year_of_graduation': "Année de Diplôme",
        'university_specialty': "Spécialité Universitaire",
        'year_of_application': "Année de Candidature",
        'cycle': "Cycle Annuel",
        'cycles': ['I Cycle', 'II Cycle'],
        'application_mode': "Mode de Candidature",
        'academic_performance': "📊 Performance Académique",
        'final_grade': "Note Finale",
        'final_grade_help': "Note obtenue lors du processus d'admission",
        'predict_button': "🔮 Prédire l'Admission",
        'pdf_button': "📄 Générer PDF",
        'error_found': "❌ Les erreurs suivantes ont été trouvées :",
        'complete_fields': "❌ Veuillez remplir tous les champs obligatoires",
        'success_data': "✅ Données traitées avec succès !",
        'prediction_result': "🔮 Résultat de la Prédiction",
        'likely_admission': "🎉 **ADMISSION PROBABLE**",
        'unlikely_admission': "❌ **ADMISSION IMPROBABLE**",
        'admission_probability': "Probabilité d'Admission",
        'model_info': "🤖 Modèle utilisé : {model} (R² = 86,31%)",
        'prediction_error': "❌ Erreur de prédiction : {e}",
        'prediction_hint': "💡 Assurez-vous que les valeurs saisies sont valides pour le modèle entraîné.",
        'factor_analysis': "📈 Analyse des Facteurs",
        'excellent_grade': "✅ Note excellente (≥15)",
        'average_grade': "⚠️ Note moyenne (12-14)",
        'low_grade': "❌ Note faible (<12)",
        'favorable_mode': "✅ Mode favorable",
        'typical_age': "✅ Âge typique pour la candidature",
        'early_application': "✅ Candidature précoce",
        'late_application': "⚠️ Plusieurs années depuis le diplôme",
        'pdf_generation': "📄 Génération de PDF",
        'pdf_success': "✅ PDF généré avec succès !",
        'pdf_error': "❌ Erreur lors de la génération du PDF : {e}",
        'data_summary': "📋 Résumé des Données",
        'sidebar_info': "ℹ️ Informations sur le Modèle",
        'sidebar_model': "**Modèle :** {model}\n\n**R² Score :** 86,31%\n**Précision :** 91,97%\n**Caractéristiques :** 9 variables\n\n**Meilleur modèle entraîné avec des données réelles**",
        'sidebar_report': "📄 Télécharger le Rapport d'Entraînement",
        'footer': "---",
        'language': "Langue",
        'spanish': "Espagnol",
        'english': "Anglais",
        'french': "Français",
        'german': "Allemand",
        'italian': "Italien",
        'portuguese': "Portugais",
        'russian': "Russe",
        'chinese': "Chinois",
        'japanese': "Japonais",
        'value': "Valeur",
        'pdf_download': "Télécharger PDF"
    },
    'de': {  # German
        'main_title': "🎓 Universitätszulassungs-Vorhersage",
        'subtitle': "**Vorhersagesystem basierend auf maschinellem Lernen**",
        'student_info': "📋 Studenteninformationen",
        'year_of_birth': "Geburtsjahr",
        'sex': "Geschlecht",
        'sexs': ['Männlich', 'Weiblich'],
        'school_name': "Schulname",
        'year_of_graduation': "Abschlussjahr",
        'university_specialty': "Universitätsspezialisierung",
        'year_of_application': "Bewerbungsjahr",
        'cycle': "Jahreszyklus",
        'cycles': ['I Zyklus', 'II Zyklus'],
        'application_mode': "Bewerbungsmodus",
        'academic_performance': "📊 Akademische Leistung",
        'final_grade': "Endnote",
        'final_grade_help': "Note erhalten im Zulassungsprozess",
        'predict_button': "🔮 Zulassung Vorhersagen",
        'pdf_button': "📄 PDF Generieren",
        'error_found': "❌ Folgende Fehler wurden gefunden:",
        'complete_fields': "❌ Bitte alle Pflichtfelder ausfüllen",
        'success_data': "✅ Daten erfolgreich verarbeitet!",
        'prediction_result': "🔮 Vorhersageergebnis",
        'likely_admission': "🎉 **WAHRSCHEINLICHE ZULASSUNG**",
        'unlikely_admission': "❌ **UNWAHRSCHEINLICHE ZULASSUNG**",
        'admission_probability': "Zulassungswahrscheinlichkeit",
        'model_info': "🤖 Verwendetes Modell: {model} (R² = 86,31%)",
        'prediction_error': "❌ Vorhersagefehler: {e}",
        'prediction_hint': "💡 Stellen Sie sicher, dass die eingegebenen Werte für das trainierte Modell gültig sind.",
        'factor_analysis': "📈 Faktoranalyse",
        'excellent_grade': "✅ Ausgezeichnete Note (≥15)",
        'average_grade': "⚠️ Durchschnittsnote (12-14)",
        'low_grade': "❌ Niedrige Note (<12)",
        'favorable_mode': "✅ Günstiger Modus",
        'typical_age': "✅ Typisches Alter für Bewerbung",
        'early_application': "✅ Frühe Bewerbung",
        'late_application': "⚠️ Mehrere Jahre seit Abschluss",
        'pdf_generation': "📄 PDF-Generierung",
        'pdf_success': "✅ PDF erfolgreich generiert!",
        'pdf_error': "❌ Fehler beim Generieren des PDFs: {e}",
        'data_summary': "📋 Datenzusammenfassung",
        'sidebar_info': "ℹ️ Modellinformationen",
        'sidebar_model': "**Modell:** {model}\\n\\n**R² Score:** 86,31%\\n**Genauigkeit:** 91,97%\\n**Merkmale:** 9 Variablen\\n\\n**Bestes Modell mit echten Daten trainiert**",
        'sidebar_report': "📄 Trainingsbericht Herunterladen",
        'footer': "---",
        'language': "Sprache",
        'spanish': "Spanisch",
        'english': "Englisch",
        'french': "Französisch",
        'german': "Deutsch",
        'value': "Wert",
        'pdf_download': "PDF Herunterladen"
    },
    'it': {  # Italian
        'main_title': "🎓 Predittore di Ammissione Universitaria",
        'subtitle': "**Sistema di predizione basato su Machine Learning**",
        'student_info': "📋 Informazioni Studente",
        'year_of_birth': "Anno di Nascita",
        'sex': "Sesso",
        'sexs': ['Maschile', 'Femminile'],
        'school_name': "Nome Scuola",
        'year_of_graduation': "Anno di Laurea",
        'university_specialty': "Specialità Universitaria",
        'year_of_application': "Anno di Candidatura",
        'cycle': "Ciclo Annuale",
        'cycles': ['I Ciclo', 'II Ciclo'],
        'application_mode': "Modalità di Candidatura",
        'academic_performance': "📊 Prestazioni Accademiche",
        'final_grade': "Voto Finale",
        'final_grade_help': "Voto ottenuto nel processo di ammissione",
        'predict_button': "🔮 Predici Ammissione",
        'pdf_button': "📄 Genera PDF",
        'error_found': "❌ Sono stati trovati i seguenti errori:",
        'complete_fields': "❌ Per favore completa tutti i campi obbligatori",
        'success_data': "✅ Dati elaborati con successo!",
        'prediction_result': "🔮 Risultato della Predizione",
        'likely_admission': "🎉 **AMMISSIONE PROBABILE**",
        'unlikely_admission': "❌ **AMMISSIONE IMPROBABILE**",
        'admission_probability': "Probabilità di Ammissione",
        'model_info': "🤖 Modello utilizzato: {model} (R² = 86,31%)",
        'prediction_error': "❌ Errore di predizione: {e}",
        'prediction_hint': "💡 Assicurati che i valori inseriti siano validi per il modello addestrato.",
        'factor_analysis': "📈 Analisi dei Fattori",
        'excellent_grade': "✅ Voto eccellente (≥15)",
        'average_grade': "⚠️ Voto medio (12-14)",
        'low_grade': "❌ Voto basso (<12)",
        'favorable_mode': "✅ Modalità favorevole",
        'typical_age': "✅ Età tipica per candidatura",
        'early_application': "✅ Candidatura precoce",
        'late_application': "⚠️ Diversi anni dalla laurea",
        'pdf_generation': "📄 Generazione PDF",
        'pdf_success': "✅ PDF generato con successo!",
        'pdf_error': "❌ Errore nella generazione del PDF: {e}",
        'data_summary': "📋 Riassunto Dati",
        'sidebar_info': "ℹ️ Informazioni sul Modello",
        'sidebar_model': "**Modello:** {model}\\n\\n**R² Score:** 86,31%\\n**Precisione:** 91,97%\\n**Caratteristiche:** 9 variabili\\n\\n**Miglior modello addestrato con dati reali**",
        'sidebar_report': "📄 Scarica Rapporto di Addestramento",
        'footer': "---",
        'language': "Lingua",
        'spanish': "Spagnolo",
        'english': "Inglese",
        'french': "Francese",
        'german': "Tedesco",
        'italian': "Italiano",
        'value': "Valore",
        'pdf_download': "Scarica PDF"
    },
    'pt': {  # Portuguese
        'main_title': "🎓 Preditor de Admissão Universitária",
        'subtitle': "**Sistema de predição baseado em Machine Learning**",
        'student_info': "📋 Informações do Estudante",
        'year_of_birth': "Ano de Nascimento",
        'sex': "Sexo",
        'sexs': ['Masculino', 'Feminino'],
        'school_name': "Nome da Escola",
        'year_of_graduation': "Ano de Graduação",
        'university_specialty': "Especialidade Universitária",
        'year_of_application': "Ano de Candidatura",
        'cycle': "Ciclo Anual",
        'cycles': ['I Ciclo', 'II Ciclo'],
        'application_mode': "Modo de Candidatura",
        'academic_performance': "📊 Desempenho Acadêmico",
        'final_grade': "Nota Final",
        'final_grade_help': "Nota obtida no processo de admissão",
        'predict_button': "🔮 Predizer Admissão",
        'pdf_button': "📄 Gerar PDF",
        'error_found': "❌ Os seguintes erros foram encontrados:",
        'complete_fields': "❌ Por favor, preencha todos os campos obrigatórios",
        'success_data': "✅ Dados processados com sucesso!",
        'prediction_result': "🔮 Resultado da Predição",
        'likely_admission': "🎉 **ADMISSÃO PROVÁVEL**",
        'unlikely_admission': "❌ **ADMISSÃO IMPROVÁVEL**",
        'admission_probability': "Probabilidade de Admissão",
        'model_info': "🤖 Modelo utilizado: {model} (R² = 86,31%)",
        'prediction_error': "❌ Erro de predição: {e}",
        'prediction_hint': "💡 Certifique-se de que os valores inseridos sejam válidos para o modelo treinado.",
        'factor_analysis': "📈 Análise de Fatores",
        'excellent_grade': "✅ Nota excelente (≥15)",
        'average_grade': "⚠️ Nota média (12-14)",
        'low_grade': "❌ Nota baixa (<12)",
        'favorable_mode': "✅ Modo favorável",
        'typical_age': "✅ Idade típica para candidatura",
        'early_application': "✅ Candidatura precoce",
        'late_application': "⚠️ Vários anos desde a graduação",
        'pdf_generation': "📄 Geração de PDF",
        'pdf_success': "✅ PDF gerado com sucesso!",
        'pdf_error': "❌ Erro ao gerar PDF: {e}",
        'data_summary': "📋 Resumo dos Dados",
        'sidebar_info': "ℹ️ Informações do Modelo",
        'sidebar_model': "**Modelo:** {model}\\n\\n**R² Score:** 86,31%\\n**Precisão:** 91,97%\\n**Características:** 9 variáveis\\n\\n**Melhor modelo treinado com dados reais**",
        'sidebar_report': "📄 Baixar Relatório de Treinamento",
        'footer': "---",
        'language': "Idioma",
        'spanish': "Espanhol",
        'english': "Inglês",
        'french': "Francês",
        'german': "Alemão",
        'italian': "Italiano",
        'portuguese': "Português",
        'value': "Valor",
        'pdf_download': "Baixar PDF"
    },
    'ru': {  # Russian
        'main_title': "🎓 Предсказатель Поступления в Университет",
        'subtitle': "**Система предсказания на основе машинного обучения**",
        'student_info': "📋 Информация о Студенте",
        'year_of_birth': "Год Рождения",
        'sex': "Пол",
        'sexs': ['Мужской', 'Женский'],
        'school_name': "Название Школы",
        'year_of_graduation': "Год Окончания",
        'university_specialty': "Университетская Специальность",
        'year_of_application': "Год Подачи Заявки",
        'cycle': "Годовой Цикл",
        'cycles': ['I Цикл', 'II Цикл'],
        'application_mode': "Режим Подачи Заявки",
        'academic_performance': "📊 Академическая Успеваемость",
        'final_grade': "Итоговая Оценка",
        'final_grade_help': "Оценка, полученная в процессе поступления",
        'predict_button': "🔮 Предсказать Поступление",
        'pdf_button': "📄 Создать PDF",
        'error_found': "❌ Найдены следующие ошибки:",
        'complete_fields': "❌ Пожалуйста, заполните все обязательные поля",
        'success_data': "✅ Данные успешно обработаны!",
        'prediction_result': "🔮 Результат Предсказания",
        'likely_admission': "🎉 **ВЕРОЯТНОЕ ПОСТУПЛЕНИЕ**",
        'unlikely_admission': "❌ **МАЛОВЕРОЯТНОЕ ПОСТУПЛЕНИЕ**",
        'admission_probability': "Вероятность Поступления",
        'model_info': "🤖 Используемая модель: {model} (R² = 86,31%)",
        'prediction_error': "❌ Ошибка предсказания: {e}",
        'prediction_hint': "💡 Убедитесь, что введенные значения действительны для обученной модели.",
        'factor_analysis': "📈 Анализ Факторов",
        'excellent_grade': "✅ Отличная оценка (≥15)",
        'average_grade': "⚠️ Средняя оценка (12-14)",
        'low_grade': "❌ Низкая оценка (<12)",
        'favorable_mode': "✅ Благоприятный режим",
        'typical_age': "✅ Типичный возраст для подачи заявки",
        'early_application': "✅ Ранняя подача заявки",
        'late_application': "⚠️ Несколько лет после окончания",
        'pdf_generation': "📄 Создание PDF",
        'pdf_success': "✅ PDF успешно создан!",
        'pdf_error': "❌ Ошибка при создании PDF: {e}",
        'data_summary': "📋 Сводка Данных",
        'sidebar_info': "ℹ️ Информация о Модели",
        'sidebar_model': "**Модель:** {model}\\n\\n**R² Score:** 86,31%\\n**Точность:** 91,97%\\n**Особенности:** 9 переменных\\n\\n**Лучшая модель, обученная на реальных данных**",
        'sidebar_report': "📄 Скачать Отчет о Обучении",
        'footer': "---",
        'language': "Язык",
        'spanish': "Испанский",
        'english': "Английский",
        'french': "Французский",
        'german': "Немецкий",
        'italian': "Итальянский",
        'portuguese': "Португальский",
        'russian': "Русский",
        'value': "Значение",
        'pdf_download': "Скачать PDF"
    },
    'zh': {  # Chinese
        'main_title': "🎓 大学录取预测器",
        'subtitle': "**基于机器学习的预测系统**",
        'student_info': "📋 学生信息",
        'year_of_birth': "出生年份",
        'sex': "性别",
        'sexs': ['男性', '女性'],
        'school_name': "学校名称",
        'year_of_graduation': "毕业年份",
        'university_specialty': "大学专业",
        'year_of_application': "申请年份",
        'cycle': "年度周期",
        'cycles': ['第一周期', '第二周期'],
        'application_mode': "申请模式",
        'academic_performance': "📊 学术表现",
        'final_grade': "最终成绩",
        'final_grade_help': "录取过程中获得的成绩",
        'predict_button': "🔮 预测录取",
        'pdf_button': "📄 生成PDF",
        'error_found': "❌ 发现以下错误：",
        'complete_fields': "❌ 请填写所有必填字段",
        'success_data': "✅ 数据处理成功！",
        'prediction_result': "🔮 预测结果",
        'likely_admission': "🎉 **可能录取**",
        'unlikely_admission': "❌ **不太可能录取**",
        'admission_probability': "录取概率",
        'model_info': "🤖 使用的模型：{model} (R² = 86.31%)",
        'prediction_error': "❌ 预测错误：{e}",
        'prediction_hint': "💡 确保输入的值对训练模型有效。",
        'factor_analysis': "📈 因子分析",
        'excellent_grade': "✅ 优秀成绩 (≥15)",
        'average_grade': "⚠️ 平均成绩 (12-14)",
        'low_grade': "❌ 低成绩 (<12)",
        'favorable_mode': "✅ 有利模式",
        'typical_age': "✅ 申请的典型年龄",
        'early_application': "✅ 早期申请",
        'late_application': "⚠️ 毕业后几年",
        'pdf_generation': "📄 PDF生成",
        'pdf_success': "✅ PDF生成成功！",
        'pdf_error': "❌ 生成PDF错误：{e}",
        'data_summary': "📋 数据摘要",
        'sidebar_info': "ℹ️ 模型信息",
        'sidebar_model': "**模型：** {model}\\n\\n**R² 分数：** 86.31%\\n**准确度：** 91.97%\\n**特征：** 9个变量\\n\\n**用真实数据训练的最佳模型**",
        'sidebar_report': "📄 下载训练报告",
        'footer': "---",
        'language': "语言",
        'spanish': "西班牙语",
        'english': "英语",
        'french': "法语",
        'german': "德语",
        'italian': "意大利语",
        'portuguese': "葡萄牙语",
        'russian': "俄语",
        'chinese': "中文",
        'value': "值",
        'pdf_download': "下载PDF"
    },
    'ja': {  # Japanese
        'main_title': "🎓 大学入学予測システム",
        'subtitle': "**機械学習による予測システム**",
        'student_info': "📋 学生情報",
        'year_of_birth': "出生年",
        'sex': "性別",
        'sexs': ['男性', '女性'],
        'school_name': "学校名",
        'year_of_graduation': "卒業年",
        'university_specialty': "大学専門分野",
        'year_of_application': "申請年",
        'cycle': "年間サイクル",
        'cycles': ['第Iサイクル', '第IIサイクル'],
        'application_mode': "申請モード",
        'academic_performance': "📊 学業成績",
        'final_grade': "最終成績",
        'final_grade_help': "入学過程で得られた成績",
        'predict_button': "🔮 入学予測",
        'pdf_button': "📄 PDF生成",
        'error_found': "❌ 次のエラーが見つかりました：",
        'complete_fields': "❌ すべての必須フィールドを完成してください",
        'success_data': "✅ データが正常に処理されました！",
        'prediction_result': "🔮 予測結果",
        'likely_admission': "🎉 **入学可能性高い**",
        'unlikely_admission': "❌ **入学可能性低い**",
        'admission_probability': "入学確率",
        'model_info': "🤖 使用モデル：{model} (R² = 86.31%)",
        'prediction_error': "❌ 予測エラー：{e}",
        'prediction_hint': "💡 入力値が訓練されたモデルに有効であることを確認してください。",
        'factor_analysis': "📈 要因分析",
        'excellent_grade': "✅ 優秀な成績 (≥15)",
        'average_grade': "⚠️ 平均的な成績 (12-14)",
        'low_grade': "❌ 低い成績 (<12)",
        'favorable_mode': "✅ 有利なモード",
        'typical_age': "✅ 申請に典型的な年齢",
        'early_application': "✅ 早期申請",
        'late_application': "⚠️ 卒業から数年",
        'pdf_generation': "📄 PDF生成",
        'pdf_success': "✅ PDFが正常に生成されました！",
        'pdf_error': "❌ PDF生成エラー：{e}",
        'data_summary': "📋 データ概要",
        'sidebar_info': "ℹ️ モデル情報",
        'sidebar_model': "**モデル：** {model}\\n\\n**R² スコア：** 86.31%\\n**精度：** 91.97%\\n**特徴：** 9変数\\n\\n**実データで訓練された最良のモデル**",
        'sidebar_report': "📄 訓練レポートをダウンロード",
        'footer': "---",
        'language': "言語",
        'spanish': "スペイン語",
        'english': "英語",
        'french': "フランス語",
        'german': "ドイツ語",
        'italian': "イタリア語",
        'portuguese': "ポルトガル語",
        'russian': "ロシア語",
        'chinese': "中国語",
        'japanese': "日本語",
        'value': "値",
        'pdf_download': "PDFダウンロード"
    }
}

def get_all_supported_languages():
    """Returns all language codes that are supported"""
    return ['es', 'en', 'fr', 'de', 'it', 'pt', 'ru', 'zh', 'ja']

def get_language_name(lang_code):
    """Returns the native name of a language given its code"""
    lang_names = {
        'es': 'Español',
        'en': 'English',
        'fr': 'Français',
        'de': 'Deutsch',
        'it': 'Italiano',
        'pt': 'Português',
        'ru': 'Русский',
        'zh': '中文',
        'ja': '日本語'
    }
    return lang_names.get(lang_code, lang_code)
